name: Check deployed Go package

on:
  push:
    branches:
      - main

jobs:
  run-demo:
    name: Run LogDash Go Demo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make run script executable
        run: chmod +x check-deployed-package/run.sh

      - name: Run LogDash Go demo
        env:
          LOGDASH_API_KEY: ${{ secrets.LOGDASH_API_KEY }}
        run: ./check-deployed-package/run.sh

  test:
    name: Run Go Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run tests
        working-directory: logdash
        run: go test -v ./...
